from enum import StrEnum


class DocumentStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    REGISTERED = "REGISTERED"
    EXTRACTED = "EXTRACTED"
    CLEANED = "CLEANED"
    NORMALIZED = "NORMALIZED"
    CLASSIFIED = "CLASSIFIED"
    VALIDATED = "VALIDATED"
    CANONICAL = "CANONICAL"
    REJECTED = "REJECTED"
    ERROR = "ERROR"


class PipelineStage(StrEnum):
    ACQUISITION = "ACQUISITION"
    REGISTRATION = "REGISTRATION"
    EXTRACTION = "EXTRACTION"
    CLEANING = "CLEANING"
    NORMALIZATION = "NORMALIZATION"
    CLASSIFICATION = "CLASSIFICATION"
    VALIDATION = "VALIDATION"
    STORAGE = "STORAGE"